### ISSUE TITLE
request of data in the Path  "Model_Score_Folder"

### ISSUE THREAD

**Issue by liu666666** [WaqasSultani/AnomalyDetectionCVPR2018#1]
Thanks for the nice work!
could you please share the data in the Path  "Model_Score_Folder" , where contains Pretrained Model score on Testing videos (32 numbers for 32 temporal segments). Then i can run the Evaluate_Anomaly_Detector.m 

Besides,  i did not know why only sample the scores of 32 Shots in the Evaluate_Anomaly_Detector.m 
In my view, all shots' scores should be used to calculate the AUC.

Last ,what's your version of the keras and theano?  

Thanks again for your real wonderful job!  @WaqasSultani

**Comment by BarryBA** [comment]
Have you downloaded the dataset 'UCF_Crime'? @liu666666 
I met the error 'You don't have permission to access /cchen/UCF_Crimes.tar.gz on this server. Apache/2.4.7 (Ubuntu) Server at crcv.ucf.edu Port 80'.
Thank you !

**Comment by indranuz** [comment]
@BarryBA      the     data     set     is      in    this      link     https://webpages.uncc.edu/cchen62/dataset.html
