### ISSUE TITLE
question about training

### ISSUE THREAD

**Issue by LakyTT** [WaqasSultani/AnomalyDetectionCVPR2018#13]
Hi,thanks for your inspiring work.
      When running the code of training（TrainingAnomalyDetector_public.py),whether we need to add some parameters?such as path of videos.And I want to know whether we first extract C3D feature before training?Thanks so much

**Comment by WaqasSultani** [comment]
Yes, you need to set the paths according to the location in your PC.

Yes, in implementation, we compute C3D Features for the whole video first and then divide those features 32 segments ( which in other words corresponds to the division of the video (features) into 32 segments).

**Comment by LakyTT** [comment]
Thanks,I will try to train my own model.

**Comment by WaqasSultani** [comment]
Ok.
