### ISSUE TITLE
problem when excute Demo_Gui.py

### ISSUE THREAD

**Issue by LakyTT** [WaqasSultani/AnomalyDetectionCVPR2018#16]
Hi,
  I get this question when I run Demo_Gui.py :
('/home/lab118/jck/AnomalyDetectionCVPR2018-master/SampleVideos/Explosion008_x264.mp4', '')
Traceback (most recent call last):
  File "Demo_GUI.py", line 170, in SingleBrowse
    cap = cv2.VideoCapture(video_path)
TypeError: an integer is required (got type tuple)
could you tell me why?
thanks so  much

**Comment by LakyTT** [comment]
I solved it 
thanks

**Comment by johnyoonh** [comment]
Could you please explain what fixed it?

**Comment by darkdante2209** [comment]
bro how to solved it?
