### ISSUE TITLE
Results don't match for same videos in dataset

### ISSUE THREAD

**Issue by nerdykamil** [WaqasSultani/AnomalyDetectionCVPR2018#18]
Dear sir,

Thank you for your great work, it is really amazing. I have been able to extract features using c3d (caffe2) version. After getting the features for 32 segments, Segment_Features (32x4096). When I tested this for random robbery or accident videos from youtube. the anomaly scores were in e-06 or e-07. So I downloaded the dataset and tested for explosion008 video in dataset. I got different feature matrix and anomaly scores from those provided in sample videos of explosion8. I have shared feature vectors of sample and computed features. Kindly suggest what I could be doing wrong here and how I can reproduce exactly same results. Thank you. 
[output_segment_explosion8.txt](https://github.com/WaqasSultani/AnomalyDetectionCVPR2018/files/2588334/output_segment_explosion8.txt)
[Explosion008_x264.txt](https://github.com/WaqasSultani/AnomalyDetectionCVPR2018/files/2588335/Explosion008_x264.txt)

**Comment by WaqasSultani** [comment]
Hi,
I am not sure about the different feature vectors. Actually, I have downloaded C3D around 2 years ago. They might have changed something after that---not sure though. If that is the case, you might need to retrain the model.

**Comment by lrd8715923** [comment]
Dear sir,
@WaqasSultani,Thank you for your great work, it is really nice.I have been able to extract features using c3d (caffe2) and test results by use FC's model from you provide,i comparison the results of our results with SampleVideos from you provide.I find it is a little different.(For each images,the first results is SampleVideos from you provide,the sencond results is our)I was so confused,i use same FC model,so i guess is C3D'model made this difference.I want to get same results as SampleVideos from you provide. Could you please provide your C3D'model,please provide a download link or send to my email:424079971@qq.com. Thank you very much.
And i have a question,i feel the 3D convolution's method of your paper is a little old.I want to replace C3D with newest method(such as R(2+1)D or Multi-Fiber Net) and retrain FC'layer to Improving AUC .What do you think of that?Could you give me some instructions.
Best greetings from Liruodao.
![e8](https://user-images.githubusercontent.com/32601406/49197461-f0e02e80-f3c9-11e8-811d-896aa59db97e.jpg)
![e8a](https://user-images.githubusercontent.com/32601406/49197475-fccbf080-f3c9-11e8-8094-573ea0ba0f37.png)
![e25](https://user-images.githubusercontent.com/32601406/49197484-05242b80-f3ca-11e8-9bfc-19f528117599.png)
![e25a](https://user-images.githubusercontent.com/32601406/49197487-06edef00-f3ca-11e8-8f3d-299c168af8ee.png)
![r2](https://user-images.githubusercontent.com/32601406/49197489-08b7b280-f3ca-11e8-8c59-8e0d5b7b45a0.png)
![r2a](https://user-images.githubusercontent.com/32601406/49197490-09e8df80-f3ca-11e8-9f36-1dd4a8b4ea34.png)
![r22](https://user-images.githubusercontent.com/32601406/49197493-0c4b3980-f3ca-11e8-9e69-d121eed768ae.png)
![r22a](https://user-images.githubusercontent.com/32601406/49197497-0ead9380-f3ca-11e8-98d6-229d817ee5fa.png)
![r123](https://user-images.githubusercontent.com/32601406/49197502-11a88400-f3ca-11e8-90f1-809da4a78559.png)
![r123a](https://user-images.githubusercontent.com/32601406/49197504-12d9b100-f3ca-11e8-84ee-58da6923ae6e.png)
![s8](https://user-images.githubusercontent.com/32601406/49197506-1705ce80-f3ca-11e8-8597-992c3767a761.jpg)
![s8a](https://user-images.githubusercontent.com/32601406/49197507-1836fb80-f3ca-11e8-958c-9e77008b7983.png)
![s28](https://user-images.githubusercontent.com/32601406/49197511-1a00bf00-f3ca-11e8-8674-ac4a150518ab.png)
![s28a](https://user-images.githubusercontent.com/32601406/49197512-1b31ec00-f3ca-11e8-9e0a-24c82bb6e902.png)
![s33](https://user-images.githubusercontent.com/32601406/49197514-1cfbaf80-f3ca-11e8-8c0e-333119eb5d48.png)
![s33a](https://user-images.githubusercontent.com/32601406/49197516-1e2cdc80-f3ca-11e8-8453-6746f147cec4.png)

**Comment by Afladimir1** [comment]
> Hi,
> I am not sure about the different feature vectors. Actually, I have downloaded C3D around 2 years ago. They might have changed something after that---not sure though. If that is the case, you might need to retrain the model.


You are probably right, I'm also getting very different results. Can you provide us your version of C3D? Thanks in advance.

**Comment by junaidwahid** [comment]
@Afladimir1 same here, @WaqasSultani  can you provide your C3D version?

**Comment by nerdykamil** [comment]
Thank you for the suggestion @WaqasSultani. When I try to retrain the model using the command _python TrainingAnomalyDetector_public.py._ It throws error on line: _model.train_on_batch(inputs, targets)_. I searched the error but couldn't find anything helpful. 

My Feature matrix has shape (256,4096)
The shape of target vector is (256,)  - tried reshaping to (256,1), didn't help

The output of the train command is:

**Using Theano backend.
/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/pywt/__init__.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._extensions._pywt import *
/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/pywt/_swt.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._extensions._swt import swt_max_level, swt as _swt, swt_axis as _swt_axis
Create Model
Starting training...
number and name of folders
2
['Abnormal', 'Normal']
Loading Abnormal videos Features...
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
Loading Normal videos...
Features  loaded
Traceback (most recent call last):
  File "TrainingAnomalyDetector_public.py", line 309, in <module>
    batch_loss =model.train_on_batch(inputs, targets)
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/keras/models.py", line 719, in train_on_batch
    class_weight=class_weight)
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/keras/engine/training.py", line 1239, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 792, in __call__
    return self.function(*inputs)
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: Input of CAReduce{maximum} has zero-size on axis 0
Apply node that caused the error: Reduce{maximum}{0}(Subtensor{int64:int64:}.0)
Toposort index: 1218
Inputs types: [TensorType(float32, vector)]
Inputs shapes: [(0,)]
Inputs strides: [(4,)]
Inputs values: [array([], dtype=float32)]
Outputs clients: [[MakeVector{dtype='float32'}(max), InplaceDimShuffle{x}(max)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "TrainingAnomalyDetector_public.py", line 278, in <module>
    model.compile(loss=custom_objective, optimizer=adagrad)
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/keras/models.py", line 553, in compile
    **kwargs)
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/keras/engine/training.py", line 630, in compile
    sample_weight, mask)
  File "/home/lfd/anaconda3/envs/c3d_caffe2_try3/lib/python2.7/site-packages/keras/engine/training.py", line 332, in weighted
    score_array = fn(y_true, y_pred)
  File "TrainingAnomalyDetector_public.py", line 222, in custom_objective
    sub_max = T.concatenate([sub_max, T.stack(T.max(Feat_Score))])         # Keep the maximum score of scores of all instances in a Bag (video)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.**

**Comment by nerdykamil** [comment]
Keeping the batch_size 60 I was able to train the model. Thank you :+1:

**Comment by DenisN03** [comment]
@nerdykamil, can you tell me how you prepared the features? What should the folder structure be for training?

**Comment by mrkstt** [comment]
Hi @nerdykamil , on your side how long the training process has done?. I'm using GTX 1050 Ti, and it's already two days, and the training is still ongoing.

**Comment by hali6779** [comment]
Hi @lrd8715923, may I have some guidance on how to replace C3D with other methods or do you have any sample code for that? Thanks in advance.
