### ISSUE TITLE
Dropbox link is broken for anomaly train split

### ISSUE THREAD

**Issue by eozer** [WaqasSultani/AnomalyDetectionCVPR2018#19]
When I've downloaded the UCF_Crimes-Train-Test-Split.zip file [Dropbox link](https://www.dropbox.com/sh/75v5ehq4cdg5g5g/AABvnJSwZI7zXb8_myBA0CLHa?dl=0) inside Anomaly_Detection_splits folder, the anomaly train file is empty. Is it possible to upload it again?

**Comment by eozer** [comment]
Actually I just downloaded from Option 2 as well, and it is also empty file.

**Comment by WaqasSultani** [comment]
Please find the file over here:
https://github.com/WaqasSultani/AnomalyDetectionCVPR2018/blob/master/Anomaly_Train.txt
