### ISSUE TITLE
About environments

### ISSUE THREAD

**Issue by henniekim** [WaqasSultani/AnomalyDetectionCVPR2018#2]
Hello!
I have been studying your paper and I'd like to demo your code.
But I have trouble in about python environments.
Could you please upload the environmnets list that you used? 
Thank you in advance.

**Comment by WaqasSultani** [comment]
Hi I have used the following
 

Keras version 1.1.0

Theano 1.0.2

Python 3

Ubuntu 16.04

**Comment by henniekim** [comment]
Thanks for quick reply :) but actually I would like to know about the details (e.g OpenCV version, etc...)

**Comment by Hgeun** [comment]
![image](https://user-images.githubusercontent.com/33209778/43253277-906f1a3e-90ff-11e8-858f-7ddf0f480d18.png)
We have this error.

**Comment by indrango** [comment]
You can refactor PyQT4 to PyQT5 to running demo script

**Comment by WaqasSultani** [comment]
Ok. Thanks
