### ISSUE TITLE
custom loss function bug

### ISSUE THREAD

**Issue by Pr0d19y** [WaqasSultani/AnomalyDetectionCVPR2018#23]
Hello, 
seems like you have a bug in line 267 in TrainingAnomalyDetector_public.py

sub_z = T.maximum(1 - Sub_Abn + Sub_Nor[ii], 0)

shouldn't it be Sub_Abn[ii]?

**Comment by WaqasSultani** [comment]
No, it is not a bug. Please check out the code again

**Comment by VivaaindreanNg** [comment]
> Hello,
> seems like you have a bug in line 267 in TrainingAnomalyDetector_public.py


Hello there,

I've executed the TrainingAnomalyDetector_public.py, and it raised a TypeError as shown below:

>   File "D:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 671, in __bool__
>     raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
> 
> TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

Is it because of the keras/theano version? I'm using keras=1.2.2 & theano=1.0.4 by the way. I couldn't exactly pinpoint on why it raised the error.

**Comment by Pr0d19y** [comment]
Hello, 
WaqasSultani
I did check and I also reread your paper... seems like there is a mismatch. or perhaps the for loop is wrong?

**Comment by Pr0d19y** [comment]
You are right! sorry about that :)

**Comment by yldrmBtn** [comment]
Please, can you explain why it is not a bug? Formulation in the code differs from the formulation given in the paper
