### ISSUE TITLE
error about theano reshape and other things

### ISSUE THREAD

**Issue by muyue1238** [WaqasSultani/AnomalyDetectionCVPR2018#3]
Hi Mr.Sultani, very like your paper and idea, but I ran into some problems while I'm trying to run your code. I think the main problem is that my packages' version are different from yours. I've installed keras, theano and python etc using anaconda, here's my packages info:
`theano                    1.0.2            py35h6bb024c_0  `
`keras                     1.1.1                    py35_0  `
`python                    3.5.5                hc3d631a_4  `
this is the main packages you mentioned and i didn't find keras 1.1.0 so I used 1.1.1 instead. I suppose tensorflow is not required but anaconda installed it while I was trying to install keras. And here's tensorflow's info:
`tensorflow                1.9.0           mkl_py35h5be851a_1  `

There's some else packages that are required, such as path.py. I created a new enviroment for this paper, so I need to install everything this work needs.
After install everything I think may be of help, I ran "python TrainingAnomalyDetector_public.py " ans I ran this problem:
`Traceback (most recent call last):
  File "TrainingAnomalyDetector_public.py", line 281, in <module>
    model.compile(loss=custom_objective, optimizer=adagrad)
  File "/home/xwbian/anaconda2/envs/keras/lib/python3.5/site-packages/keras/models.py", line 553, in compile
    **kwargs)
  File "/home/xwbian/anaconda2/envs/keras/lib/python3.5/site-packages/keras/engine/training.py", line 630, in compile
    sample_weight, mask)
  File "/home/xwbian/anaconda2/envs/keras/lib/python3.5/site-packages/keras/engine/training.py", line 332, in weighted
    score_array = fn(y_true, y_pred)
  File "TrainingAnomalyDetector_public.py", line 204, in custom_objective
    y_true = T.flatten(y_true)
  File "/home/xwbian/anaconda2/envs/keras/lib/python3.5/site-packages/theano/tensor/basic.py", line 5276, in flatten
    x_reshaped = x.reshape(dims)
AttributeError: 'Tensor' object has no attribute 'reshape'`

I'm not sure what is causing this problem, so would you mind to take a look?
Look forward to your concern and really hope that you can make a more detailed README. Great work, please let me say it again.

**Comment by WaqasSultani** [comment]
You can install Keras 1.1.0 using the following command
pip install keras==1.1.0

**Comment by muyue1238** [comment]
I used python3.5 and many errors came to me, but when I try python2.7, everything looks fine. So maybe that's the problem.

**Comment by Anirudh58** [comment]
@muyue1238 Can you tell me what you did to fix the issue? I am facing the same problem. 

These are my versions. I am running it on a jupyter notebook with python3
'2.2.4' - Keras
'1.0.3' - Theano
'1.10.0' - Tensorflow

> Hi Mr.Sultani, very like your paper and idea, but I ran into some problems while I'm trying to run your code. I think the main problem is that my packages' version are different from yours. I've installed keras, theano and python etc using anaconda, here's my packages info:
> `theano 1.0.2 py35h6bb024c_0 `
> `keras 1.1.1 py35_0 `
> `python 3.5.5 hc3d631a_4 `
> this is the main packages you mentioned and i didn't find keras 1.1.0 so I used 1.1.1 instead. I suppose tensorflow is not required but anaconda installed it while I was trying to install keras. And here's tensorflow's info:
> `tensorflow 1.9.0 mkl_py35h5be851a_1 `
> 
> There's some else packages that are required, such as path.py. I created a new enviroment for this paper, so I need to install everything this work needs.
> After install everything I think may be of help, I ran "python TrainingAnomalyDetector_public.py " ans I ran this problem:
> `Traceback (most recent call last): File "TrainingAnomalyDetector_public.py", line 281, in <module> model.compile(loss=custom_objective, optimizer=adagrad) File "/home/xwbian/anaconda2/envs/keras/lib/python3.5/site-packages/keras/models.py", line 553, in compile **kwargs) File "/home/xwbian/anaconda2/envs/keras/lib/python3.5/site-packages/keras/engine/training.py", line 630, in compile sample_weight, mask) File "/home/xwbian/anaconda2/envs/keras/lib/python3.5/site-packages/keras/engine/training.py", line 332, in weighted score_array = fn(y_true, y_pred) File "TrainingAnomalyDetector_public.py", line 204, in custom_objective y_true = T.flatten(y_true) File "/home/xwbian/anaconda2/envs/keras/lib/python3.5/site-packages/theano/tensor/basic.py", line 5276, in flatten x_reshaped = x.reshape(dims) AttributeError: 'Tensor' object has no attribute 'reshape'`
> 
> I'm not sure what is causing this problem, so would you mind to take a look?
> Look forward to your concern and really hope that you can make a more detailed README. Great work, please let me say it again.

**Comment by trqminh** [comment]
> I used python3.5 and many errors came to me, but when I try python2.7, everything looks fine. So maybe that's the problem.

can you tell me what is the version of keras, theano and tensorflow when you use python 2.7

**Comment by mvk07** [comment]
Please use keras 1.1.0 with theano 1.0.2 backend. 

Refer [here](https://keras.io/backend/) on how to change backend.

**Comment by sonal-511** [comment]
Changing tensorflow backend to theano backend worked for me.I was running it in colab so will mention the steps I followed.These steps one should follow after installing keras 1.1.0 
1.pip install theano==1.0.2
2./usr/local/lib/python3.6/dist-packages/keras/backend/__init.py__
3.change _BACKEND='tensorflow ' ------------->_BACKEND= 'theano' 
4. _BACKEND = _backend --------> _BACKEND = "theano"

**Comment by dersugiritlioglu** [comment]
> Changing tensorflow backend to theano backend worked for me.I was running it in colab so will mention the steps I followed.These steps one should follow after installing keras 1.1.0
> 1.pip install theano==1.0.2
> 2./usr/local/lib/python3.6/dist-packages/keras/backend/**init.py**
> 3.change _BACKEND='tensorflow ' ------------->_BACKEND= 'theano'
> 4. _BACKEND = _backend --------> _BACKEND = "theano"

This idea seems to be working, but without changing the `keras.json` file, this did not work for me.
Its location is `'/home/<myusername>/.keras/keras.json'`.
If you do not want to change the default, then you might insert `_backend = 'theano'` line of code in `__init__.py` after the line `_backend = _config.get('backend', _BACKEND)` (forcing) here in my case:
`/home/<myusername>/anaconda3/envs/<myenvname>/lib/python3.7/site-packages/keras/backend/__init__.py`
