### ISSUE TITLE
The paper says you used a C3D pretrained model but we can't find it anywhere

### ISSUE THREAD

**Issue by mourad1081** [WaqasSultani/AnomalyDetectionCVPR2018#30]
Figure 1. You use a pre-trained C3D convnet. On which database have you pretrained your C3D network? 

I found a pretrained model based on UCF101 and another one based on Sports1m but your paper does not provide any further explanations regarding the pretraining. Your code does not show how you have extracted features also.

Could you please give us a link technically explaining how you extracted the features?

Thank you

**Comment by kjsr7** [comment]
You should be using the Sports1m one.
First you need to extract the features using the C3D-V1.0 and then run the 'Save_C3DFeatures_32Segments.m' of this repository to save the features into 32 segments for each video. [This ](https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag/edit)technically explains how to extract the features.

**Comment by VVVVictorJ** [comment]
Hi,
I think  you may be talk about the pretrained-model. https://www.dropbox.com/s/vr8ckp0pxgbldhs/conv3d_deepnetA_sport1m_iter_1900000?dl=0

**Comment by mourad1081** [comment]
Thank you both of you for your answers, they both help me.

**Comment by cervantes-loves-ai** [comment]
> Hi,
> I think you may be talk about the pretrained-model. https://www.dropbox.com/s/vr8ckp0pxgbldhs/conv3d_deepnetA_sport1m_iter_1900000?dl=0

can you provide .fc files also?

**Comment by wzy1845** [comment]
> Hi,
> I think you may be talk about the pretrained-model. https://www.dropbox.com/s/vr8ckp0pxgbldhs/conv3d_deepnetA_sport1m_iter_1900000?dl=0

Hello, how to use this pre training model to extract features? Is there any code?thans!
