### ISSUE TITLE
Ambiguity in the paper regarding the generations of bags (txt file)

### ISSUE THREAD

**Issue by mourad1081** [WaqasSultani/AnomalyDetectionCVPR2018#32]
It is written: (in the implementation details section):  "_We compute C3D features for every 16-frame video clip._" - However, the flow diagram shows that there are 32 segments videos ( = 32 instances) per video (per bag). Does it means that the frames per instances is related to the number of frames of the video being processed. Am I wrong somewhere? (that is, only some frames for a short video and a huge amount of frame for a very long video)

I am confused since I don't know how you exactly generated the txt files durig the C3D features. By looking at your samples, it seems that all files contain 32 x 4096D. Can I assume that you did something like : 

```
for each video V
    1. bag = list()
    2. nb_frames_in_one_instance = int (nb_frames in V / 32)
    3. for i in range(32)
        3.1. f = generate C3D features for the frames (i*nb_frames_in_one_instance) to (i*nb_frames_in_one_instance) + nb_frames_in_one_instance.
        3.2. bag.append(f)
    4. save bag in a text file

```
?

I do not understand why they say "_every 16-frame video clip_".

**Comment by mourad1081** [comment]
Found the answere here: https://github.com/WaqasSultani/AnomalyDetectionCVPR2018/issues/20

**Comment by poweryin** [comment]
@mourad1081,Hi,I have the same confusion,if the video is short,I contains 320 frames.Then I have 320/16 =20clips.Howeverr,the code shows divide the video to 32segments,I don't understand how it dived into 32(20<32)

Best Wishes
Thanks
