### ISSUE TITLE
How do I install a c3d model?

### ISSUE THREAD

**Issue by PrincyX** [WaqasSultani/AnomalyDetectionCVPR2018#45]

**Comment by PrincyX** [comment]
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-12c68d5431da> in <module>()
     23 from scipy.spatial.distance import cdist,pdist,squareform
     24 import theano.sandbox
---> 25 import c3D_model
     26 import Initialization_function
     27 from moviepy.editor import VideoFileClip

ModuleNotFoundError: No module named 'c3D_model'`

**Comment by rajanjitenpatel** [comment]
You can comment it out. Without c3D_model, it working fine.

** import congif. that work for Demo.py**
import configparser
import collections
import time
import csv
from math import factorial
import os
from os import listdir
import skimage.transform
from skimage import color
from os.path import isfile, join
import numpy as np
import numpy
from datetime import datetime
from scipy.spatial.distance import cdist,pdist,squareform
import theano.sandbox
**#import c3d
#import Initialization_function
#from moviepy.editor import VideoFileClip**
from IPython.display import Image, display
import matplotlib.pyplot as plt
import cv2
import os, sys
import pickle
**# from PyQt5 import QtCore, QtGui, QtWidgets**   
seed = 7
numpy.random.seed(seed)


I recommend to run this project on Keras 1.1.2 version. To Install use
`pip install keras==1.1.2` 

For your information.
I have created [C3D feature extraction using Google Colab](https://github.com/rajanjitenpatel/C3D_feature_extraction) for particular to this project. you can check this out. It is easy and faster way to extract video feature.

**Comment by RajdeepPy** [comment]
It got this error after I made the changes that you suggested
```
NameError                                 Traceback (most recent call last)
<ipython-input-28-5d8fcdc00a42> in <module>()
    112     return  AllFeatures
    113 
--> 114 class PrettyWidget(QtGui.QWidget):
    115 
    116     def __init__(self):

NameError: name 'QtGui' is not defined
```

**Comment by PrincyX** [comment]
@PrincyX, replace
```
PrettyWidget(QtGui.QWidget)
```
with
```
PrettyWidget(QtWidgets.QWidget)
```
According to the documentation, this is a version error between PyQt4 and PyQt5

**Comment by AndyHon** [comment]
@rajanjitenpatel Thank you for your work. Do you need caffe to extract video features?I never successfully installed caffe。

**Comment by rajanjitenpatel** [comment]
Yes, @AndyHon Caffe is required for C3D video features extraction.

In [C3D feature extraction using Google Colab](https://github.com/rajanjitenpatel/C3D_feature_extraction) project use [C3D_feature_extraction_Colab.ipynb](https://github.com/rajanjitenpatel/C3D_feature_extraction/blob/master/C3D_feature_extraction_Colab.ipynb) and follow **Setup C3D model** steps to install it. *No Additional installation required for Caffe.
