### ISSUE TITLE
Anyone tried it by extracting features from i3d.

### ISSUE THREAD

**Issue by sanchit2843** [WaqasSultani/AnomalyDetectionCVPR2018#54]

**Comment by ataafarin** [comment]
did you find any answer?
thanks

**Comment by sanchit2843** [comment]
I tried it, the performance was not adequate. I think it was because I couldn't find pretrained weights of the sports-1m dataset. The pretrained weight I used was kinetics-400. Please tell me if you are able to find weights of any good video recognition model on sports-1m.
