### ISSUE TITLE
SyntaxError: invalid syntax in line 310 in TrainingAnomalyDetector_public.py

### ISSUE THREAD

**Issue by cervantes-loves-ai** [WaqasSultani/AnomalyDetectionCVPR2018#57]
Don't understand why got this error while running TrainingAnomalyDetector_public.py

TrainingAnomalyDetector_public.py", line 310
    print "These iteration=" + str(total_iterations) + ") took: " + str(datetime.now() - time_before) + ", with loss of " + str(batch_loss)
                           ^
SyntaxError: invalid syntax

thanks in advance

**Comment by ylztjsy** [comment]
In python3, you must use the bracket to print, like print(...) 

PS. If u are working on this paper, maybe we can discuss it.
My wechat number is TJTJTJW, you can attach words like 'github' for verification.

**Comment by cervantes-loves-ai** [comment]
thank you for your informations

ps. don't have wechat better mail, sarkeribrahim gmail
