### ISSUE TITLE
error loading normal and abnormal C3D video features/  inputs, targets = load_dataset_Train_batch(AbnormalPath, NormalPath)

### ISSUE THREAD

**Issue by Villjoie** [WaqasSultani/AnomalyDetectionCVPR2018#68]
why when i experiment with my dataset it gives this error??
help me please!!!

/usr/bin/python3 /home/socialab/PycharmProjects/Master/V_master/anotar_imagens/AnomalyDetectionCVPR2018-master/TrainingAnomalyDetector_public.py
Using Theano backend.
Create Model
Starting training...
Loading Abnormal videos Features...
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
 Abnormal Features  loaded
Loading Normal videos...
Traceback (most recent call last):
  File "/home/socialab/PycharmProjects/Master/V_master/anotar_imagens/AnomalyDetectionCVPR2018-master/TrainingAnomalyDetector_public.py", line 284, in <module>
    inputs, targets = load_dataset_Train_batch(AbnormalPath, NormalPath)  # Load normal and abnormal video C3D features
  File "/home/socialab/PycharmProjects/Master/V_master/anotar_imagens/AnomalyDetectionCVPR2018-master/TrainingAnomalyDetector_public.py", line 140, in load_dataset_Train_batch
    VideoPath = os.path.join(AllVideos_Path, All_Videos[iv])
IndexError: list index out of range

Can someone help me with the resolution?

**Comment by Villjoie** [comment]
should i split my dataset in half or how do i do that?

**Comment by mh-y** [comment]
> should i split my dataset in half or how do i do that?

excuse. How did you fix it?

**Comment by Villjoie** [comment]
@mh-y 
I solved the problem by dividing the dataset in two directories, one directory I put the videos with the actions present and the other of videos that have no actions.
it worked correctly

**Comment by mh-y** [comment]
Thanks to you, i solved the problem.

**Comment by AhmedEldemoksy** [comment]
@mh-y  excuse. How did you fix it?

**Comment by mh-y** [comment]
dear Ahmed Eldemoksy
 
I don't remember exactly.
At that time, I was a beginner in deep learning, and I remember correcting mistakes in the process of dividing folders and routing datasets to solve errors.
Please set the path correctly so that the program does not become "out of index". The file in that path is remembered as an error that occurs when it is not recognized correctly.
I hope it helps. 
-----Original Message-----
