### ISSUE TITLE
link is broken in readme

### ISSUE THREAD

**Issue by JHyunB** [WaqasSultani/AnomalyDetectionCVPR2018#75]
![image](https://user-images.githubusercontent.com/36959292/94523111-b072c580-026b-11eb-8a97-53bb48746733.png)
I think this will have to change from 'http://crcv.ucf.edu/projects/real-world/' to 'https://crcv.ucf.edu/projects/real-world/'

**Comment by WaqasSultani** [comment]
Thanks
