### ISSUE TITLE
Issue regarding conversion of model.json file to model.pb file

### ISSUE THREAD

**Issue by Zain-Gill123** [WaqasSultani/AnomalyDetectionCVPR2018#83]
Hello. I am newbie. Just getting into this stuff. And I am stuck at conversion of model.json to model.pb format. Is there any way this is possible. I've been searching the inter webs for the past week and haven't stumbled upon anything.  

I want to convert the model.json to a .blob file and from what I have learnt there is no way it can be done directly. I have to go via model.pb file.

Any type of help would be highly appreciated.
-Zain

**Comment by yassinesamet** [comment]
have you solve the problem ??

**Comment by Zain-Gill123** [comment]
@yassinesamet Yes, I solved it. I was converting the models wrongly. Plus, model.json file was not the one that was to be converted.

**Comment by yassinesamet** [comment]
@Zain-Gill123 did you convert the model to tensorrt ??

**Comment by Zain-Gill123** [comment]
@yassinesamet Sorry for late reply mate. No I did not convert it to TensorRT. I had misinterpreted the model file owing to my lack of experience.
